Blog/Controllers/BloginfoController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Net.Http.Formatting;
using Blog.Models;


namespace Blog.Controllers
{
    public class BloginfoController : Controller
    {

        MyContext a1=new MyContext();

        
        public ActionResult BlogInfo()
        {
            List<Bloginfo> l = new List<Bloginfo>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44352/api/");
                var responseTask = client.GetAsync("BlogInfo");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readData = result.Content.ReadAsAsync<Bloginfo[]>();
                    readData.Wait();
                    var emp = readData.Result;
                    foreach (var item in emp)
                    {
                        l.Add(new Bloginfo
                        {
                            BlogId = item.BlogId,
                            Title = item.Title,
                            Subject = item.Subject,
                            DateOfCreation = item.DateOfCreation,
                            BlogUrl = item.BlogUrl,
                            EmpemailId = item.EmpemailId

                        });
                    }
                }
            }
            return View(l);

        }

        public ActionResult Blogs()
        {
            List<Bloginfo> l = new List<Bloginfo>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44352/api/");
                var responseTask = client.GetAsync("BlogInfo");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readData = result.Content.ReadAsAsync<Bloginfo[]>();
                    readData.Wait();
                    var emp = readData.Result;
                    var ans = TempData["emailid"].ToString();
                    foreach (var item in emp)
                    {
                        if (item.EmpemailId == ans)
                        {
                            l.Add(new Bloginfo
                            {
                                BlogId = item.BlogId,
                                Title = item.Title,
                                Subject = item.Subject,
                                DateOfCreation = item.DateOfCreation,
                                BlogUrl = item.BlogUrl,
                                EmpemailId = item.EmpemailId

                            }); }
                    }
                }
            }
            return View(l);

        }

        public ActionResult AddBlogInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddBlogInfo(Bloginfo blog)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44352/api/BlogInfo");
                var b = new BlogInfo { BlogId = blog.BlogId, Title = blog.Title, Subject = blog.Subject, DateOfCreation = blog.DateOfCreation, BlogUrl = blog.BlogUrl, EmpEmailId = blog.EmpemailId };
                var Post = client.PostAsJsonAsync<Bloginfo>(client.BaseAddress, blog);
                Post.Wait();
                var result = Post.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readtask = result.Content.ReadAsAsync<Bloginfo>();
                    readtask.Wait();
                    var dataInserted = readtask.Result;
                }
            }
            return RedirectToAction("BlogInfo");
        }

        public ActionResult EmpLogin()
        {
            
            return View();

        }

        [HttpPost]
        public ActionResult EmpLogin(FormCollection collection)
        {
            List<Empinfo> l = new List<Empinfo>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44352/api/");
                var responseTask = client.GetAsync("EmpInfo");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readData = result.Content.ReadAsAsync<Empinfo[]>();
                    readData.Wait();
                    var emp = readData.Result;
                    foreach (var item in emp)
                    {
                        l.Add(new Empinfo { EmailId=item.EmailId,PassCode=item.PassCode });

                    }
                }
            }
            var ans = l.Find(s => s.EmailId == Request["EmailId"]);
            if (ans != null)
            {
                if (ans.PassCode==Convert.ToInt32(Request["Passcode"]))
                {
                    TempData["emailid"] = ans.EmailId;
                    return RedirectToAction("Blogs");
                }
                else
                {
                    ViewBag.msg = "IncorrectPassword";
                }

            }
            else
            {
                ViewBag.msg = "EmailId Not Found";
            }
            return View();

        }
        public ActionResult LogOut()
        {
            return RedirectToAction("BlogInfo");
        }


       

    }
}

Blog/Views/Shared/_BlogsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blog Tracker", "BlogInfo", "BlogInfo", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Blog List", "BlogInfo", "BlogInfo", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("LogOut", "Logout", "BlogInfo", new { area = "" }, new { @class = "navbar-brand" })


            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Blog/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BlogTracker", "BlogInfo", "BlogInfo", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("EmployeeList", "EmpInfo", "EmpInfo", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("LogOut", "Logout", "BlogInfo", new { area = "" }, new { @class = "navbar-brand" })


            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BlogTracker", "BlogInfo", "BlogInfo", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Home", "BlogInfo", "Bloginfo", new { area = " " }, new { @class = "navbar-brand" })
               
            </div>
            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Login
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            
                            <li>@Html.ActionLink("Admin", "AdminLogin", "EmpInfo")</li>
                            <li>@Html.ActionLink("Employee", "EmpLogin", "BlogInfo")</li>
                        </ul>
                    </div>
                </ul>
            </div>

           
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>